# Generated by Django 6.0.6 on 2026-06-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the assignment.', max_length=200)),
                ('description', models.TextField(help_text='Full assignment brief and instructions for students.')),
                ('due_date', models.DateTimeField(help_text='Deadline by which students must submit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive assignments are closed and do not accept new submissions.')),
                ('max_file_size_mb', models.IntegerField(default=10, help_text='Maximum allowed submission file size in megabytes.')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Display title for this file (e.g. 'Week 3 — Lecture Notes').", max_length=200)),
                ('file', models.FileField(help_text='The actual file. Stored in MEDIA_ROOT/class_files/.', upload_to='class_files/')),
                ('description', models.TextField(blank=True, help_text='Optional description of the file contents.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes. Set automatically on upload.')),
            ],
            options={
                'verbose_name': 'Class File',
                'verbose_name_plural': 'Class Files',
                'db_table': 'class_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The submitted file. Stored in MEDIA_ROOT/submissions/.', upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_late', models.BooleanField(default=False, help_text='True if the submission was made after the assignment due date.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the student to the lecturer.', null=True)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
