# Generated by Django 6.0.6 on 2026-06-24 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='class_room',
            field=models.ForeignKey(help_text='The class this assignment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classes.class'),
        ),
    ]
