# Generated by Django 6.0.6 on 2026-07-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
