# Generated by Django 6.0.6 on 2026-06-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional document brief (PDF, Word, etc.) for students to view.', null=True, upload_to='assignment_attachments/'),
        ),
    ]
