# Generated by Django 6.0.6 on 2026-07-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_submission_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='file',
            name='group',
        ),
        migrations.RemoveField(
            model_name='file',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
