# Generated by Django 6.0.6 on 2026-07-02 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VMTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name shown in the VM catalogue (e.g. AutoCAD Workstation).', max_length=150)),
                ('description', models.TextField(help_text='Explains what this template is for and who should request it.')),
                ('cpu_cores', models.IntegerField(help_text='Number of virtual CPU cores allocated to this VM type.')),
                ('ram_gb', models.IntegerField(help_text='RAM in gigabytes allocated to this VM type.')),
                ('storage_gb', models.IntegerField(help_text='Disk size in gigabytes allocated to this VM type.')),
                ('software_list', models.JSONField(default=list, help_text="JSON array of pre-installed software names (e.g. ['AutoCAD 2024', 'Revit']).")),
                ('os', models.CharField(help_text="Operating system (e.g. 'Windows 10', 'Ubuntu 22.04').", max_length=100)),
                ('is_available', models.BooleanField(default=True, help_text='If False, this template is hidden from the student catalogue.')),
                ('icon', models.CharField(blank=True, help_text="Emoji or icon identifier for the catalogue card (e.g. '🖥️').", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VM Template',
                'verbose_name_plural': 'VM Templates',
                'db_table': 'vm_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Auto-generated friendly name for this VM (e.g. 'AutoCAD-Denis-001').", max_length=150)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('deleted', 'Deleted')], default='provisioning', help_text='Current lifecycle status of this virtual machine.', max_length=20)),
                ('proxmox_vm_id', models.IntegerField(blank=True, help_text='The real Proxmox VM ID. Null when running in simulation mode.', null=True)),
                ('cpu_usage', models.FloatField(default=0.0, help_text='Current CPU utilisation percentage (0–100). Updated by vm_orchestrator.')),
                ('ram_usage', models.FloatField(default=0.0, help_text='Current RAM utilisation percentage (0–100). Updated by vm_orchestrator.')),
                ('allocated_at', models.DateTimeField(auto_now_add=True, help_text='When the student first requested this VM.')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the VM last transitioned to RUNNING status.', null=True)),
                ('stopped_at', models.DateTimeField(blank=True, help_text='When the VM last transitioned to STOPPED status.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional internal notes or error messages from the orchestrator.', null=True)),
                ('owner', models.ForeignKey(help_text='The student who owns this VM.', on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(help_text='The template this VM was built from.', on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='vms.vmtemplate')),
            ],
            options={
                'verbose_name': 'Virtual Machine',
                'verbose_name_plural': 'Virtual Machines',
                'db_table': 'virtual_machines',
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='stopped', max_length=20)),
                ('compute_hours_used', models.FloatField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms.virtualmachine')),
                ('vm_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vms.vmtemplate')),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
