# Generated by Django 6.0.6 on 2026-07-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='guacamole_connection_id',
            field=models.CharField(blank=True, default='', help_text='Guacamole connection identifier for remote desktop access.', max_length=100),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='ip_address',
            field=models.CharField(blank=True, default='', help_text='IP address of the running VM (populated by Proxmox guest agent).', max_length=50),
        ),
        migrations.AddField(
            model_name='vmtemplate',
            name='is_real',
            field=models.BooleanField(default=False, help_text='If True, launches real Proxmox VM. If False, simulated.'),
        ),
        migrations.AddField(
            model_name='vmtemplate',
            name='proxmox_template_id',
            field=models.IntegerField(blank=True, help_text='Proxmox VM ID of the template to clone. Null = simulated.', null=True),
        ),
    ]
