# Generated by Django 6.0.6 on 2026-07-04 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_virtualmachine_guacamole_connection_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VMPoolEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxmox_vmid', models.IntegerField(help_text='Proxmox VM ID of this clone.', unique=True)),
                ('ip_address', models.CharField(blank=True, default='', help_text='IP address assigned to this VM.', max_length=50)),
                ('guacamole_connection_id', models.CharField(blank=True, default='', help_text='Guacamole connection identifier for remote access.', max_length=100)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('ready', 'Ready'), ('assigned', 'Assigned'), ('error', 'Error')], default='creating', help_text='Current pool lifecycle status.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When this VM was assigned to a user.', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='The user currently using this VM.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pool_vms', to=settings.AUTH_USER_MODEL)),
                ('assigned_vm', models.ForeignKey(blank=True, help_text='The linked VirtualMachine record when assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_entry', to='vms.virtualmachine')),
                ('template', models.ForeignKey(help_text='The template this pool VM was cloned from.', on_delete=django.db.models.deletion.CASCADE, related_name='pool_entries', to='vms.vmtemplate')),
            ],
            options={
                'verbose_name': 'VM Pool Entry',
                'verbose_name_plural': 'VM Pool Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
