# Generated by Django 6.0.6 on 2026-07-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_vmpoolentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmtemplate',
            name='monthly_cap',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max monthly charge TZS', max_digits=10),
        ),
        migrations.AddField(
            model_name='vmtemplate',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per hour in TZS', max_digits=10),
        ),
        migrations.AddField(
            model_name='vmtemplate',
            name='template_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('server', 'Server')], default='desktop', max_length=20),
        ),
    ]
