# Generated by Django 6.0.6 on 2026-07-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0004_vmtemplate_monthly_cap_vmtemplate_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmtemplate',
            name='auto_refill_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vmtemplate',
            name='last_pool_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmtemplate',
            name='target_pool_size',
            field=models.IntegerField(default=2, help_text='Number of VMs to keep pre-cloned and ready'),
        ),
    ]
