# Generated by Django 6.0.6 on 2026-07-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0006_workspacefreeusage_workspacesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='access_reason',
            field=models.CharField(blank=True, default='', help_text="How the current/last launch was granted: 'subscription', 'free_hour', or 'paid'. Used at stop time to decide whether to log free-hour usage.", max_length=20),
        ),
    ]
