# Generated by Django 6.0.6 on 2026-08-02 00:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0007_workspace_access_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='last_accessed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last genuine launch (any launch path: free, paid, subscription, or power-up). The activity signal for idle-workspace detection.'),
        ),
        migrations.CreateModel(
            name='WorkspaceIdleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('first_warning', 'First Warning'), ('final_warning', 'Final Warning'), ('deleted', 'Deleted')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_notifications', to='vms.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'notification_type')},
            },
        ),
    ]
