# Generated by Django 6.0.6 on 2026-08-02 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0008_alter_workspace_last_accessed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacesubscription',
            name='user',
        ),
        migrations.AddField(
            model_name='vmtemplate',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat monthly subscription price in TZS for unlimited access to this template', max_digits=10),
        ),
        migrations.CreateModel(
            name='TemplateSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.vmtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'template')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceHoursBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.vmtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'template')},
            },
        ),
        migrations.DeleteModel(
            name='WorkspaceFreeUsage',
        ),
        migrations.DeleteModel(
            name='WorkspaceSubscription',
        ),
    ]
