# Generated by Django 6.0.8 on 2026-08-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0009_remove_workspacesubscription_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='status',
            field=models.CharField(choices=[('provisioning', 'Provisioning'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('deleted', 'Deleted')], db_index=True, default='provisioning', help_text='Current lifecycle status of this virtual machine.', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], db_index=True, default='stopped', max_length=20),
        ),
    ]
