# Generated by Django 6.0.8 on 2026-08-19 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0010_alter_virtualmachine_status_alter_workspace_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopEnvironmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short machine key, e.g. 'xfce', 'gnome-zorin'.", max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('session_command', models.TextField(help_text='The real, verified /etc/xrdp/startwm.sh content for this environment.')),
                ('fix_script', models.TextField(blank=True, help_text='Real, proven setup commands to run before writing session_command (package installs, cursor-fix file creation, permission fixes).')),
                ('default_apps', models.JSONField(blank=True, default=list, help_text="Suggested default app package names for this environment, e.g. ['firefox'].")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Desktop Environment Profile',
                'verbose_name_plural': 'Desktop Environment Profiles',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCreationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proxmox_vmid', models.IntegerField(blank=True, null=True)),
                ('cpu_cores', models.IntegerField(default=2)),
                ('ram_gb', models.IntegerField(default=4)),
                ('disk_gb', models.IntegerField(default=20)),
                ('iso_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('vm_creating', 'Creating VM'), ('awaiting_os_install', 'Awaiting OS Install'), ('configuring', 'Applying Configuration'), ('installing_apps', 'Installing Applications'), ('finalizing', 'Finalizing Template'), ('verifying', 'Verifying Template'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='vm_creating', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('log', models.JSONField(blank=True, default=list, help_text='Real, timestamped step log for admin visibility.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_template_id', models.IntegerField(blank=True, help_text='proxmox_vmid of the verified, finalized template, once known.', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('desktop_environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vms.desktopenvironmentprofile')),
            ],
            options={
                'verbose_name': 'Template Creation Job',
                'verbose_name_plural': 'Template Creation Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
