# Generated by Django 6.0.8 on 2026-08-20 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0012_seed_desktop_environment_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsoDownloadTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upid', models.CharField(max_length=255, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False, help_text="Set once the real Proxmox task is confirmed stopped, so it stops being offered as 'active'.")),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ISO Download Tracking',
                'verbose_name_plural': 'ISO Download Tracking',
                'ordering': ['-created_at'],
            },
        ),
    ]
