# Generated by Django 6.0.8 on 2026-08-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0013_isodownloadtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmtemplate',
            name='os_family',
            field=models.CharField(blank=True, default='', help_text="Simple OS family key used to pick a real, correctly-licensed icon (e.g. 'ubuntu', 'debian', 'parrot', 'zorin', 'windows'). Distinct from the free-text 'os' display string.", max_length=30),
        ),
    ]
