# Generated by Django 6.0.6 on 2026-08-23 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        ('vms', '0014_vmtemplate_os_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmtemplate',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Optional. Null = platform-wide template, visible to everyone (existing behavior, unchanged). Set = scoped to this university only — used for course-specific templates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='university.university'),
        ),
    ]
