# Generated by Django 6.0.6 on 2026-08-23 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_templaterequest'),
        ('vms', '0015_vmtemplate_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecreationjob',
            name='template_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='university.templaterequest'),
        ),
        migrations.AddField(
            model_name='templatecreationjob',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_jobs', to='university.university'),
        ),
    ]
