# Generated by Django 6.0.8 on 2026-08-24 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0016_templatecreationjob_template_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecreationjob',
            name='template_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('server', 'Server (CLI only)')], default='desktop', help_text="'desktop' = the existing flow (a chosen DesktopEnvironmentProfile is configured and streamed via RDP). 'server' = CLI-only/headless: no desktop environment at all, ongoing access is via Guacamole SSH only, never RDP/VNC.", max_length=20),
        ),
        migrations.AlterField(
            model_name='templatecreationjob',
            name='desktop_environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vms.desktopenvironmentprofile'),
        ),
    ]
