# Generated by Django 6.0.8 on 2026-08-25 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_course_schedule_day_course_schedule_time'),
        ('vms', '0017_template_creation_job_server_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecreationjob',
            name='template_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('server', 'Server (CLI only)'), ('windows', 'Windows')], default='desktop', help_text="'desktop' = the existing flow (a chosen DesktopEnvironmentProfile is configured and streamed via RDP). 'server' = CLI-only/headless: no desktop environment at all, ongoing access is via Guacamole SSH only, never RDP/VNC. 'windows' = a genuine third path — no DesktopEnvironmentProfile/fix_script (desktop_environment stays null, same as 'server'), Windows' own native RDP server instead of xrdp, VirtIO drivers instead of a Linux guest agent, Sysprep instead of machine-id clearing at finalize time.", max_length=20),
        ),
        migrations.AlterField(
            model_name='vmtemplate',
            name='os_family',
            field=models.CharField(blank=True, default='', help_text="Simple OS family key used to pick a real, correctly-licensed icon (e.g. 'ubuntu', 'debian', 'parrot', 'zorin', 'windows') — distinct from the free-text 'os' display string.", max_length=30),
        ),
        migrations.AlterField(
            model_name='vmtemplate',
            name='template_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('server', 'Server'), ('windows', 'Windows')], default='desktop', max_length=20),
        ),
        migrations.AlterField(
            model_name='vmtemplate',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Optional. Null = platform-wide template, visible to everyone (existing behavior, unchanged). Set = scoped to this university only — used for course-specific templates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='university.university'),
        ),
    ]
