# Generated by Django 6.0.6 on 2026-08-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('workspace_ready', 'Workspace Ready'), ('workspace_stopped', 'Workspace Stopped'), ('hours_balance_low', 'Hours Balance Running Low'), ('session_invite', 'Session Invite'), ('payment_confirmed', 'Payment Confirmed'), ('workspace_idle', 'Workspace Idle Warning'), ('direct_message', 'Direct Message'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
