# Generated by Django 6.0.6 on 2026-08-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('workspace_ready', 'Workspace Ready'), ('workspace_stopped', 'Workspace Stopped'), ('hours_balance_low', 'Hours Balance Running Low'), ('session_invite', 'Session Invite'), ('payment_confirmed', 'Payment Confirmed'), ('workspace_idle', 'Workspace Idle Warning'), ('direct_message', 'Direct Message'), ('system', 'System'), ('template_request_approved', 'Template Request Approved'), ('template_request_rejected', 'Template Request Rejected'), ('template_request_completed', 'Template Request Completed')], default='system', max_length=30),
        ),
    ]
