# Generated by Django 6.0.6 on 2026-06-25 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_coursestream'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text="Department the user belongs to (e.g. 'Computer Engineering').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stream',
            field=models.ForeignKey(blank=True, help_text='The DIT programme stream the student belongs to (e.g. BENG22 COE-2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.coursestream'),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.IntegerField(blank=True, help_text='Current year of study (e.g. 2, 3, 4). Students only.', null=True),
        ),
    ]
