# Generated by Django 6.0.6 on 2026-07-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='can_create_groups',
            new_name='can_host_sessions',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='can_create_sessions',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='can_publish_templates',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_concurrent_sessions',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_workspaces',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_session_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='host_plan',
            field=models.CharField(choices=[('none', 'No Host Plan'), ('personal', 'Personal Host'), ('pro', 'Pro Host'), ('institution', 'Institution')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('personal_host', 'Personal Host'), ('pro_host', 'Pro Host'), ('institution', 'Institution')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', help_text='Determines which dashboard and permissions this user has.', max_length=20),
        ),
    ]
