# Generated by Django 6.0.6 on 2026-06-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_department_coursestream_group_number_and_more'),
        ('users', '0002_user_department_user_stream_user_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department the user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='classes.department'),
        ),
    ]
