# Generated by Django 6.0.6 on 2026-06-26 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_remove_class_stream_remove_coursestream_nta_level_and_more'),
        ('users', '0003_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='The academic programme the user is enrolled in (e.g. Bachelor of Computer Engineering).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.programme'),
        ),
    ]
