# Generated by Django 6.0.6 on 2026-07-07 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_password_reset_code_user_password_reset_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_hours_low',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_session_invite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_workspace_ready',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('key_prefix', models.CharField(help_text='First 8 chars for identification', max_length=10)),
                ('name', models.CharField(default='Default', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.CharField(blank=True, default='', max_length=45)),
                ('calls_today', models.IntegerField(default=0)),
                ('calls_reset_at', models.DateTimeField(blank=True, null=True)),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=True)),
                ('can_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Token',
            },
        ),
    ]
