# Generated by Django 6.0.6 on 2026-07-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_notify_announcements_user_notify_hours_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='key_prefix',
            field=models.CharField(help_text='First 8 chars for identification', max_length=20),
        ),
    ]
