# Generated by Django 6.0.6 on 2026-07-09 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_apitoken_key_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_suspended', 'User Suspended'), ('user_reactivated', 'User Reactivated'), ('user_role_changed', 'User Role Changed'), ('template_created', 'Template Created'), ('template_updated', 'Template Updated'), ('template_deleted', 'Template Deleted'), ('price_changed', 'Price Changed'), ('vm_stopped', 'VM Force Stopped'), ('session_ended', 'Session Force Ended'), ('payment_refunded', 'Payment Refunded'), ('config_changed', 'System Config Changed'), ('backup_triggered', 'Backup Triggered'), ('maintenance_toggled', 'Maintenance Mode Toggled')], max_length=50)),
                ('description', models.TextField()),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
