# Generated by Django 6.0.6 on 2026-07-29 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_avatar_url_user_firebase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, help_text="The subscription plan this payment purchased, if any. Null for non-subscription payments (session hosting, session extensions) that aren't tied to a plan tier.", null=True, on_delete=django.db.models.deletion.PROTECT, to='users.subscriptionplan'),
        ),
    ]
