# Generated by Django 6.0.6 on 2026-07-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('session_hosting', 'Session Hosting'), ('session_extend', 'Session Extend'), ('workspace_hourly', 'Workspace Pay-Per-Hour'), ('workspace_subscription', 'Workspace Monthly Subscription')], max_length=30, null=True),
        ),
    ]
