# Generated by Django 6.0.6 on 2026-07-31 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_payment_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='host_plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_host',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
