# Generated by Django 6.0.6 on 2026-08-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_usersubscription_plan_remove_payment_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('session_hosting', 'Session Hosting'), ('session_extend', 'Session Extend'), ('workspace_hours_purchase', 'Workspace Hours Purchase'), ('workspace_template_subscription', 'Workspace Template Subscription')], max_length=40, null=True),
        ),
    ]
