# Generated by Django 6.0.6 on 2026-08-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_direct_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_workspace_idle',
            field=models.BooleanField(default=True),
        ),
    ]
