# Generated by Django 6.0.6 on 2026-08-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(choices=[('user_suspended', 'User Suspended'), ('user_reactivated', 'User Reactivated'), ('user_role_changed', 'User Role Changed'), ('template_created', 'Template Created'), ('template_updated', 'Template Updated'), ('template_deleted', 'Template Deleted'), ('price_changed', 'Price Changed'), ('vm_stopped', 'VM Force Stopped'), ('session_ended', 'Session Force Ended'), ('payment_refunded', 'Payment Refunded'), ('config_changed', 'System Config Changed'), ('backup_triggered', 'Backup Triggered'), ('maintenance_toggled', 'Maintenance Mode Toggled'), ('university_approved', 'University Approved'), ('university_rejected', 'University Rejected'), ('university_invoice_created', 'University Invoice Created'), ('university_invoice_status_changed', 'University Invoice Status Changed')], max_length=50),
        ),
    ]
