# Generated by Django 6.0.6 on 2026-07-02 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('vms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text="Short action code (e.g. 'VM_STARTED', 'LOGIN', 'FILE_UPLOADED').", max_length=100)),
                ('description', models.TextField(help_text='Human-readable description of what happened.')),
                ('metadata', models.JSONField(default=dict, help_text='Arbitrary JSON context for the event (e.g. VM ID, file name).')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this event occurred.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='The client IP address associated with this event.', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed this action. Null for system-level events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this exam (e.g. 'CAD Mid-Term Exam').", max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended')], default='scheduled', help_text='Current state of this exam session.', max_length=20)),
                ('starts_at', models.DateTimeField(help_text='Scheduled start time for the exam.')),
                ('ends_at', models.DateTimeField(help_text='Scheduled end time for the exam.')),
                ('restrict_internet', models.BooleanField(default=True, help_text='Block internet access inside student VMs during this exam.')),
                ('restrict_copy_paste', models.BooleanField(default=True, help_text='Disable clipboard (copy-paste) inside student VMs during this exam.')),
                ('instructions', models.TextField(blank=True, default='', help_text='Specific instructions for students during this exam.')),
                ('grace_period_minutes', models.IntegerField(default=0, help_text='Number of minutes before starts_at that students are allowed to connect.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_vm_template', models.ForeignKey(blank=True, help_text='Restrict students to using only VMs from this template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions', to='vms.vmtemplate')),
                ('group', models.ForeignKey(help_text='The group this exam applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='classes.group')),
                ('lecturer', models.ForeignKey(help_text='The lecturer who controls this exam.', limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Session',
                'verbose_name_plural': 'Exam Sessions',
                'db_table': 'exam_sessions',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('session_type', models.CharField(choices=[('workshop', 'Workshop'), ('lab', 'Laboratory'), ('exam', 'Exam / Assessment'), ('lecture', 'Lecture'), ('study_group', 'Study Group'), ('training', 'Training'), ('other', 'Other')], default='workshop', max_length=20)),
                ('invite_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('invite_link', models.CharField(blank=True, max_length=200)),
                ('is_public', models.BooleanField(default=False)),
                ('is_exam_mode', models.BooleanField(default=False)),
                ('max_participants', models.IntegerField(default=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('restrict_internet', models.BooleanField(default=False)),
                ('restrict_copy_paste', models.BooleanField(default=False)),
                ('allow_late_submission', models.BooleanField(default=True)),
                ('submission_type', models.CharField(choices=[('none', 'No Submission'), ('file', 'File Upload'), ('snapshot', 'VM Snapshot'), ('both', 'File + Snapshot')], default='none', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='classes.group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
                ('required_vm_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms.vmtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('connecting', 'Connecting'), ('active', 'Active'), ('disconnected', 'Disconnected'), ('terminated', 'Terminated')], default='connecting', help_text='Current connection state of this session.', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the session was initiated.')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the session ended. Null if still active.', null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Total connected time in seconds. Updated on session close.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='The client IP address that initiated the connection.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary JSON context for the session (e.g. session token).')),
                ('user', models.ForeignKey(help_text='The user who opened this session.', on_delete=django.db.models.deletion.CASCADE, related_name='remote_sessions', to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(help_text='The virtual machine this session connects to.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='vms.virtualmachine')),
            ],
            options={
                'verbose_name': 'Remote Session',
                'verbose_name_plural': 'Remote Sessions',
                'db_table': 'remote_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('active', 'Active'), ('disconnected', 'Disconnected'), ('submitted', 'Submitted'), ('removed', 'Removed')], default='joined', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='session_submissions/')),
                ('vm_snapshot_id', models.CharField(blank=True, max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='vdi_sessions.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_participations', to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms.virtualmachine')),
            ],
            options={
                'unique_together': {('session', 'user')},
            },
        ),
    ]
