# Generated by Django 6.0.6 on 2026-07-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdi_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='group',
        ),
        migrations.AddField(
            model_name='livesession',
            name='allow_participant_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livesession',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='livesession',
            name='record_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livesession',
            name='show_participant_list',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ExamSession',
        ),
    ]
