# Generated by Django 6.0.6 on 2026-06-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdi_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotesession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary JSON context for the session (e.g. session token).'),
        ),
    ]
