# Generated by Django 6.0.6 on 2026-06-24 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdi_sessions', '0002_remotesession_metadata'),
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='allowed_vm_template',
            field=models.ForeignKey(blank=True, help_text='Restrict students to using only VMs from this template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions', to='vms.vmtemplate'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='grace_period_minutes',
            field=models.IntegerField(default=0, help_text='Number of minutes before starts_at that students are allowed to connect.'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Specific instructions for students during this exam.'),
        ),
    ]
