# Generated by Django 6.0.6 on 2026-07-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdi_sessions', '0002_remove_livesession_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='duration_hours',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='livesession',
            name='restrictions',
            field=models.JSONField(blank=True, default=dict, help_text='Session control settings'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
