# Generated by Django 6.0.6 on 2026-06-26 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_remove_studentpracticalaccess_practical_session_and_more'),
        ('vdi_sessions', '0003_examsession_allowed_vm_template_and_more'),
        ('vms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('session_type', models.CharField(default='practical', max_length=50)),
                ('submission_type', models.CharField(default='file_upload', max_length=50)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('instructions', models.TextField(blank=True, default='')),
                ('max_concurrent_vms', models.IntegerField(default=30)),
                ('auto_terminate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_sessions', to='classes.class')),
                ('lecturer', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='practical_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('required_vm_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practical_sessions', to='vms.vmtemplate')),
            ],
            options={
                'verbose_name': 'Practical Session',
                'verbose_name_plural': 'Practical Sessions',
                'db_table': 'practical_sessions',
                'ordering': ['-scheduled_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentPracticalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_attended', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='practical_submissions/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=10)),
                ('lecturer_notes', models.TextField(blank=True, default='')),
                ('practical_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_access', to='vdi_sessions.practicalsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='practical_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Practical Access',
                'verbose_name_plural': 'Student Practical Access',
                'db_table': 'student_practical_access',
                'ordering': ['-practical_session__scheduled_date'],
                'unique_together': {('practical_session', 'student')},
            },
        ),
    ]
