# Generated by Django 6.0.6 on 2026-07-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdi_sessions', '0003_livesession_duration_hours_livesession_restrictions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='amount_paid_tzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='livesession',
            name='auto_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livesession',
            name='hours_purchased',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='livesession',
            name='scheduled_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
