# Generated by Django 6.0.6 on 2026-07-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdi_sessions', '0004_livesession_amount_paid_tzs_livesession_auto_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionparticipant',
            name='is_being_controlled',
            field=models.BooleanField(default=False),
        ),
    ]
