# Generated by Django 6.0.6 on 2026-06-26 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vdi_sessions', '0004_practicalsession_studentpracticalaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicalsession',
            options={'ordering': ['-start_time'], 'verbose_name': 'Practical Session', 'verbose_name_plural': 'Practical Sessions'},
        ),
        migrations.AlterModelOptions(
            name='studentpracticalaccess',
            options={'ordering': ['-practical_session__start_time'], 'verbose_name': 'Student Practical Access', 'verbose_name_plural': 'Student Practical Access'},
        ),
        migrations.RemoveField(
            model_name='practicalsession',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='practicalsession',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='practicalsession',
            name='end_time',
        ),
        migrations.AddField(
            model_name='practicalsession',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='practicalsession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='practicalsession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practicalsession',
            name='submission_type',
            field=models.CharField(default='both', max_length=50),
        ),
    ]
