# Generated by Django 6.0.6 on 2026-08-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdi_sessions', '0005_sessionparticipant_is_being_controlled'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list, help_text='Domains reachable through the network lockdown when restrict_internet is on'),
        ),
    ]
