# Generated by Django 6.0.6 on 2026-08-23 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        ('vdi_sessions', '0006_livesession_allowed_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Optional. Null = regular individual session (existing behavior, unchanged). Set = a real class session tied to a university course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='university.course'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20),
        ),
    ]
