# Generated by Django 6.0.6 on 2026-08-23 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vms', '0014_vmtemplate_os_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text="e.g. 'CS', 'BA'", max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='department_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="'Intro to Programming'", max_length=200)),
                ('code', models.CharField(help_text="'CS101'", max_length=20)),
                ('default_restrictions', models.JSONField(blank=True, default=dict, help_text="clipboard/file-transfer/network-lockdown defaults for this course's sessions.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms.vmtemplate')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university.department')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('admin', 'University Admin')], default='student', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='university.department')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Brief description submitted with the access request.')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('seats_allocated', models.IntegerField(default=0)),
                ('price_per_seat_tzs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('semester', 'Per Semester'), ('annual', 'Annual')], default='semester', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, help_text='The real user account that administers this university.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_universities', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_universities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='university.university'),
        ),
        migrations.CreateModel(
            name='UniversityInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_tzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='university.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer')], max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='university.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('course', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('university', 'code')},
        ),
        migrations.CreateModel(
            name='UniversityAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('admin', 'University Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='university.department')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_affiliations', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='university.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_affiliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'university', 'department', 'role')},
            },
        ),
    ]
