# Generated by Django 6.0.6 on 2026-08-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='max_ram_gb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='max_storage_gb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='max_vcpu_cores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='requested_ram_gb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='requested_storage_gb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='requested_vcpu_cores',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
