# Generated by Django 6.0.6 on 2026-08-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_templaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule_day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
