# Generated by Django 6.0.6 on 2026-07-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('group_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('institution', 'Institution')], default='private', max_length=20)),
                ('invite_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('invite_link', models.CharField(blank=True, max_length=200)),
                ('max_members', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(default=list)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='group_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_group', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('owner', 'Owner')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
