# Generated by Django 6.0.6 on 2026-06-24 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(help_text='The lecturer who owns this class.', limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='class_room',
            field=models.ForeignKey(help_text='The class this student is enrolled in.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.class'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='student',
            field=models.ForeignKey(help_text='The student who is enrolled.', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classenrollment',
            unique_together={('student', 'class_room')},
        ),
    ]
