# Generated by Django 6.0.6 on 2026-06-25 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='academic_year',
            field=models.CharField(blank=True, help_text='e.g. 2025/2026', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.CharField(blank=True, help_text='Department hosting the class.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='max_students',
            field=models.IntegerField(default=60, help_text='Maximum number of students allowed'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.IntegerField(default=1, help_text='Semester 1 or 2'),
        ),
        migrations.AddField(
            model_name='class',
            name='stream',
            field=models.CharField(blank=True, help_text='e.g. COE-2', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from the student.')),
                ('rejection_reason', models.TextField(blank=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='classes.class')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrollment_requests',
                'ordering': ['-requested_at'],
                'unique_together': {('student', 'class_room')},
            },
        ),
    ]
