# Generated by Django 6.0.6 on 2026-06-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_academic_year_class_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short unique stream code, e.g. 'BENG22 COE-2'.", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Full descriptive name, e.g. 'Computer Engineering Group 2'.", max_length=100)),
                ('department', models.CharField(help_text="Department this stream belongs to, e.g. 'Computer Engineering'.", max_length=100)),
                ('year_of_study', models.IntegerField(help_text='Year of study (e.g. 2, 3, or 4).')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive streams are hidden from registration dropdowns.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Stream',
                'verbose_name_plural': 'Course Streams',
                'db_table': 'course_streams',
                'ordering': ['department', 'year_of_study', 'code'],
            },
        ),
    ]
