# Generated by Django 6.0.6 on 2026-07-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_groupresource'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together=set(),
        ),
    ]
