# Generated by Django 6.0.6 on 2026-07-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_remove_submission_assignment_remove_file_group_and_more'),
        ('classes', '0004_alter_groupmembership_unique_together'),
        ('vdi_sessions', '0002_remove_livesession_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupresource',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupresource',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
        migrations.DeleteModel(
            name='GroupResource',
        ),
    ]
