# Generated by Django 6.0.6 on 2026-06-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_coursestream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short unique department code, e.g. 'CS'.", max_length=10, unique=True)),
                ('name', models.CharField(help_text="Full department name, e.g. 'Computer Studies'.", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the department.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='coursestream',
            name='group_number',
            field=models.IntegerField(default=1, help_text='Group number (COE-1, COE-2, etc.).'),
        ),
        migrations.AddField(
            model_name='coursestream',
            name='nta_level',
            field=models.CharField(blank=True, default='', help_text="NTA Level, e.g. 'NTA Level 8'.", max_length=20),
        ),
        migrations.AddField(
            model_name='coursestream',
            name='programme',
            field=models.CharField(blank=True, default='', help_text="Programme name, e.g. 'Bachelor of Computer Engineering'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='stream',
            field=models.ForeignKey(blank=True, help_text='Course stream for the class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='classes.coursestream'),
        ),
        migrations.AlterField(
            model_name='coursestream',
            name='code',
            field=models.CharField(help_text="Short unique stream code, e.g. 'BENG22 COE-2'.", max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='coursestream',
            name='name',
            field=models.CharField(help_text="Full descriptive name, e.g. 'Bachelor of Computer Engineering Year 2 Group 1'.", max_length=150),
        ),
        migrations.AlterField(
            model_name='coursestream',
            name='year_of_study',
            field=models.IntegerField(default=1, help_text='Year of study (e.g. 1, 2, 3, or 4).'),
        ),
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department hosting the class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='classes.department'),
        ),
        migrations.AlterField(
            model_name='coursestream',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this stream belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='classes.department'),
        ),
    ]
