# Generated by Django 6.0.6 on 2026-06-26 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_department_coursestream_group_number_and_more'),
        ('vms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='coursestream',
            name='nta_level',
        ),
        migrations.AddField(
            model_name='class',
            name='streams',
            field=models.ManyToManyField(blank=True, help_text='Course streams that take this class.', related_name='classes_assigned', to='classes.coursestream'),
        ),
        migrations.CreateModel(
            name='PracticalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title for this practical session.', max_length=200)),
                ('scheduled_date', models.DateField(help_text='Date of the practical session.')),
                ('start_time', models.TimeField(help_text='Start time of the session.')),
                ('end_time', models.TimeField(help_text='End time of the session.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current state of this practical session.', max_length=20)),
                ('instructions', models.TextField(blank=True, default='', help_text='Instructions for students during this practical session.')),
                ('max_concurrent_vms', models.IntegerField(default=30, help_text='Maximum number of VMs that can run simultaneously in this session.')),
                ('auto_terminate', models.BooleanField(default=True, help_text='Whether to auto-terminate student VMs when the session ends.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_room', models.ForeignKey(help_text='The class this practical session is for.', on_delete=django.db.models.deletion.CASCADE, related_name='practical_sessions', to='classes.class')),
                ('lecturer', models.ForeignKey(help_text='The lecturer who owns this practical session.', limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='practical_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('vm_template', models.ForeignKey(blank=True, help_text='VM template students will use in this session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practical_sessions', to='vms.vmtemplate')),
            ],
            options={
                'verbose_name': 'Practical Session',
                'verbose_name_plural': 'Practical Sessions',
                'db_table': 'practical_sessions',
                'ordering': ['-scheduled_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short unique programme code, e.g. 'BCOE', 'ODIT'.", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Full programme name, e.g. 'Bachelor of Computer Engineering'.", max_length=150)),
                ('nta_level', models.CharField(blank=True, default='', help_text="NTA Level, e.g. 'NTA Level 8'.", max_length=20)),
                ('duration_years', models.IntegerField(default=4, help_text='Expected programme duration in years (e.g. 3 for diploma, 4 for degree).')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this programme is currently offered.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(help_text='Department offering this programme.', on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='classes.department')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'db_table': 'programmes',
                'ordering': ['department', 'code'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Programme this class belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='classes.programme'),
        ),
        migrations.AlterField(
            model_name='coursestream',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Programme this stream belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='classes.programme'),
        ),
        migrations.CreateModel(
            name='StudentPracticalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_attended', models.BooleanField(default=False, help_text='Whether the student actually connected to a VM.')),
                ('joined_at', models.DateTimeField(blank=True, help_text='When the student first connected.', null=True)),
                ('left_at', models.DateTimeField(blank=True, help_text='When the student disconnected.', null=True)),
                ('submission_file', models.FileField(blank=True, help_text='Submitted work file.', null=True, upload_to='practical_submissions/')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When work was submitted.', null=True)),
                ('grade', models.CharField(blank=True, default='', help_text='Optional grade for the practical.', max_length=10)),
                ('lecturer_notes', models.TextField(blank=True, default='', help_text='Optional notes from the lecturer.')),
                ('practical_session', models.ForeignKey(help_text='The practical session.', on_delete=django.db.models.deletion.CASCADE, related_name='student_access', to='classes.practicalsession')),
                ('student', models.ForeignKey(help_text='The student.', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='practical_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Practical Access',
                'verbose_name_plural': 'Student Practical Access',
                'db_table': 'student_practical_access',
                'ordering': ['-practical_session__scheduled_date'],
                'unique_together': {('practical_session', 'student')},
            },
        ),
    ]
