# Generated by Django 6.0.6 on 2026-06-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_remove_class_stream_remove_coursestream_nta_level_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentpracticalaccess',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentpracticalaccess',
            name='practical_session',
        ),
        migrations.RemoveField(
            model_name='studentpracticalaccess',
            name='student',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='nta_level',
        ),
        migrations.AddField(
            model_name='programme',
            name='level',
            field=models.CharField(choices=[('diploma', 'Diploma (NTA 4-6)'), ('bachelor', 'Bachelor (NTA 7-8)'), ('master', 'Master (NTA 9)')], default='bachelor', help_text='Programme level (e.g. bachelor, diploma).', max_length=20),
        ),
        migrations.AddField(
            model_name='programme',
            name='nta_range',
            field=models.CharField(blank=True, help_text="NTA range, e.g. 'NTA Level 4-6'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='programme',
            name='duration_years',
            field=models.IntegerField(default=3, help_text='Expected programme duration in years (e.g. 3 for diploma, 4 for degree).'),
        ),
        migrations.DeleteModel(
            name='PracticalSession',
        ),
        migrations.DeleteModel(
            name='StudentPracticalAccess',
        ),
    ]
