# Generated by Django 6.0.6 on 2026-06-27 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_remove_studentpracticalaccess_practical_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('official', 'Official Class'), ('working_group', 'Working Group / Lab')], default='working_group', help_text='Type of class: official (admin-created) or working_group (lecturer-created).', max_length=20),
        ),
        migrations.AddField(
            model_name='class',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this class record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
