# Generated by Django 6.0.6 on 2026-06-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_class_class_type_class_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='year_of_study',
            field=models.IntegerField(blank=True, help_text='Year of study (1-4). Used for official classes.', null=True),
        ),
    ]
